# Configurations for development, should be *only* used for development.
# Configurations defined here will override the counterparts in `default.toml`.

# This would be the default environment for development.


[development]
debug = true

[development.metrics]
dev_logger = true
dynaconf_merge = true

[development.logging]
# Any of "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
level = "DEBUG"
format = "pretty"
# For `list` or `table` settings, `dynaconf_merge` allows you to merge settings with the default
# settings. For instance, `logging.level` in this case will override its counterpart defined in
# `default_settings`.
dynaconf_merge = true
