# Configurations for development, should be *only* used for development.
# Configurations defined here will override the counterparts in `default.toml`.

# This would be the default environment for development.

[development]
debug = true
# For `list` or `table` settings, `dynaconf_merge` allows you to merge settings with the default
# settings. This enables merge for the entire `development` environment.
dynaconf_merge = true

[development.metrics]
dev_logger = true

[development.logging]
# Any of "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
level = "DEBUG"
format = "pretty"

[development.accuweather]
api_key = "test"

[development.jobs.wikipedia_indexer]
# GCS path. Combined bucket and object prefix (folders).
gcs_path = "merino-jobs-dev/wikipedia-exports"
# GCP project name where the GCS bucket lives.
gcp_project = "contextual-services-dev"

[development.jobs.navigational_suggestions]
# GCP project name that contains domain data tables
source_gcp_project = "mozdata"

[development.sports]
# List of active sports to process.
# (e.g. "NBA,NHL,EPL,UCL,etc")
# See `jobs.sportsdata_jobs.common` for list of supported sports
sports = "NBA,NHL,EPL,UCL"
api_key = "abc123"
